package com.ktds.isc.domain;

// Generated 2014. 4. 16 ?? 5:39:09 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Requestofdeletingsmartsheet generated by hbm2java
 */
public class Requestofdeletingsmartsheet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1L;
	private long	id;
	private User	user;
	private String	agentcode;
	private String	agentname;
	private String	requestorid;
	private String	requestorname;
	private String	customername;
	private String	customercode;
	private String	sheetnumber;
	private String	regdate;
	private String	requestcontent;
	private Date	modifieddate;

	public Requestofdeletingsmartsheet() {
	}

	public Requestofdeletingsmartsheet(long id, String agentcode, String agentname, String requestorid, String requestorname,
			String customername, String customercode, String requestcontent) {
		this.id = id;
		this.agentcode = agentcode;
		this.agentname = agentname;
		this.requestorid = requestorid;
		this.requestorname = requestorname;
		this.customername = customername;
		this.customercode = customercode;
		this.requestcontent = requestcontent;
	}

	public Requestofdeletingsmartsheet(long id, User user, String agentcode, String agentname, String requestorid, String requestorname,
			String customername, String customercode, String sheetnumber, String regdate, String requestcontent, Date modifieddate) {
		this.id = id;
		this.user = user;
		this.agentcode = agentcode;
		this.agentname = agentname;
		this.requestorid = requestorid;
		this.requestorname = requestorname;
		this.customername = customername;
		this.customercode = customercode;
		this.sheetnumber = sheetnumber;
		this.regdate = regdate;
		this.requestcontent = requestcontent;
		this.modifieddate = modifieddate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAgentcode() {
		return this.agentcode;
	}

	public void setAgentcode(String agentcode) {
		this.agentcode = agentcode;
	}

	public String getAgentname() {
		return this.agentname;
	}

	public void setAgentname(String agentname) {
		this.agentname = agentname;
	}

	public String getRequestorid() {
		return this.requestorid;
	}

	public void setRequestorid(String requestorid) {
		this.requestorid = requestorid;
	}

	public String getRequestorname() {
		return this.requestorname;
	}

	public void setRequestorname(String requestorname) {
		this.requestorname = requestorname;
	}

	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public String getCustomercode() {
		return this.customercode;
	}

	public void setCustomercode(String customercode) {
		this.customercode = customercode;
	}

	public String getSheetnumber() {
		return this.sheetnumber;
	}

	public void setSheetnumber(String sheetnumber) {
		this.sheetnumber = sheetnumber;
	}

	public String getRegdate() {
		return this.regdate;
	}

	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	public String getRequestcontent() {
		return this.requestcontent;
	}

	public void setRequestcontent(String requestcontent) {
		this.requestcontent = requestcontent;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

}
